language: node_js
env:
  - DBDATABASE_URL=postgres://postgres@localhost/travis_ci_test
node_js:
 - "8.11.3"
install:
 - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres